added type attribute and randomizing getCard
CSC207-2022F-UofT/course-project-the-best-monopoly-team pull request #23
Opened 2022-11-10 23:05 UTC by Leuxll

2022-11-11 01:02 UTC, benxu3 commented
looks to me like we can have Board pass in the currentPlayer and the spaceType they landed on when calling performAction through the interactor and it should be a straightforward implementation then

2022-11-11 01:02 UTC, benxu3 approved these changes

2022-11-11 01:45 UTC, derrcodes approved these changes

2022-11-16 06:34 UTC, derrcodes approved these changes
Looks like everything is fine apart from the temporary fix for performAction. I was going to bring up the fact that the ActionSpace extends cell but that's already done. I think all functions should work reasonable well and I don't see any significant issues.

2022-11-16 18:31 UTC, benxu3 requested changes

2022-11-16 18:31 UTC, benxu3 commented on src/main/java/UseCases/UseCaseInteractor.java
> +package UseCases;
Are you pulling from main? Some of these files don't look like they should be here. If possible can you rebase these commits so we get just your changes?

2022-11-16 21:45 UTC, closed without merging