ActionSpace
CSC207-2022F-UofT/course-project-the-best-monopoly-team pull request #32
Opened 2022-11-16 22:20 UTC by Leuxll

Essentially the same changes from the deleted ActionSpace branch, but due to divergence for around 25 commits, the best way to resolve this was to save files and delete the branch and remake a new one.

2022-11-16 23:17 UTC, derrcodes approved these changes
Great. Seems reasonable to make a new branch due to the divergence issue. Everyone should try to keep in mind not to dump a lot of changes (commits) at the same time to prevent this issue.

2022-11-16 23:26 UTC, benxu3 requested changes

2022-11-16 23:26 UTC, benxu3 commented on src/main/java/Entities/ActionSpace.java
> +//       /* Initialising the different Card HashMaps as we want to set these to the private instance attributes later*/
i think it would be better design if you made this code in to a helper method

2022-11-17 17:42 UTC, benxu3 approved these changes

2022-11-17 20:33 UTC, kRichard32 approved these changes
In the future, we should move the load function outside of this entity and into the use case interactor in order to oblige to clean architecture. This change is not need right now; we can move it later once the pull request for the game logic interactor and the game creation interactor has completed. Other than that, I was wondering why we need to alter the performAction method inside the cell class.

2022-11-17 20:50 UTC, kRichard32 requested changes
We might want to store the type of actionSpace inside the class itself instead of having it be passed through the performAction parameter

2022-11-17 20:50 UTC, Leuxll commented
> In the future, we should move the load function outside of this entity and into the use case interactor in order to oblige to clean architecture. This change is not need right now; we can move it later once the pull request for the game logic interactor and the game creation interactor has completed. Other than that, I was wondering why we need to alter the performAction method inside the cell class. I was thinking we could store the type of ActionSpace object inside the ActionSpace itself, rather than have the type be passed by parameter. Other than these two concerns the code looks logically done and neat.

I think the point was that cell could either be a property or an action space, so we made it into an abstract class that would be used when the board is being built, but I was unclear on that as well. As for storing the type within ActionSpace, it is already a private instance attribute so I am not quite sure what you are referring to.

2022-11-17 20:53 UTC, kRichard32 commented
Yes, using a getter method for the type rather than having the performAction method have to pass a parameter indicating the type would be better.

2022-11-17 20:53 UTC, Leuxll commented
@kRichard32 In terms of code smell, I think the methods are a little bit bloated so I might just refactor some of the code into helper functions as well.

2022-11-17 21:12 UTC, Leuxll reviewed
@kRichard32 Removed the passing of actionType within perform action method and also updated the corresponding methods in cell and also property.

2022-11-17 21:27 UTC, derrcodes approved these changes
Just looked at the changes. I agree with the changes cause it makes everything less cluttered. Making changes on each of those may also be easier later on in case.

2022-11-17 22:32 UTC, kRichard32 approved these changes
With those changes, it looks good to me. Good work!

2022-11-20 02:11 UTC, benxu3 reviewed
Take a look at my comments, otherwise I think it is good to merge. Thanks for writing JavaDoc and Unit tests.

2022-11-20 02:11 UTC, benxu3 commented on src/main/java/Entities/Cell.java
> +    public abstract String performAction(Player player, Board board);
I called the player in my Property PR to currentPlayer and merged my PR to main already. Could you change this to parameter to currentPlayer? This way we will not have any merge conflicts.

2022-11-20 02:31 UTC, merged