Board
CSC207-2022F-UofT/course-project-the-best-monopoly-team pull request #35
Opened 2022-11-18 20:00 UTC by susannah-c

New JavaDoc. Added tests for Board. Changed constructor to match Property class constructor. Changed instance attributes from arrays to Lists (players and cells).

2022-11-18 20:57 UTC, derrcodes requested changes
There are changes required for the redundancy in cells and properties. Refer to my comments for the specific changes.

2022-11-18 20:57 UTC, derrcodes commented on src/main/java/Entities/Board.java
> +    List<Cell> cells;
Having board keeps track of cells and properties might be redundant since a cell might be a property or an action space already.

2022-11-18 20:57 UTC, derrcodes commented on src/main/java/Entities/Board.java
> +    public Board(List<Player> players, List<Cell> cells, Object[][] propertyData){
Board should only take in 2 parameters: players and cells.

2022-11-28 18:40 UTC, harshkpatel commented
Removed due to future PR fixing issues

2022-11-28 18:40 UTC, closed without merging